version: '3.8'
services:
  database:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=adega
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
    expose:
      - 3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - default

volumes:
  db_data:

networks:
  default:
    driver: bridge